### ISSUE TITLE
Getting error with register.jsp page

### ISSUE THREAD

**Issue by emotinator** [emotinator/OOSDWorkshop3#4]
something like
"HTTP Status 500 - /register.jsp (line: 7, column: 0) The value for the useBean class attribute registeruser.RegisterUser is invalid."

Tried troubleshooting it.  Suggestions were to have an empty constructor in that class, but didn't seem fix anything for me.

**Comment by emotinator** [comment]
Managed to get it going on my sait laptop with some server config.

**Comment by mike-j-lindquist** [comment]
Good. I won't be able to make it in today but i'm able to work. Let me know
if you guys need anything.
